### ISSUE TITLE
Twitter video stream not working

### ISSUE THREAD

**Issue by 05tb** [met-office-lab/molab-rhino-api#25]
Videos can be downloaded from a youtube link contained within a tweet.
However these are **not immediately** displayed onto the rhino. You must navigate to the led-mapping.html page first.

Errors produced when a video url is received in a tweet:

`ERROR molab-led-rhino:app - Twitter stream error:
TypeError: Cannot read property 'forEach' of undefined
RangeNotSatisfiableError: Range Not Satisfiable
    at SendStream.error (/Users/Todd/Documents/molab-rhino-api/interface/node_modules/serve-static/node_modules/send/index.js:245:31)
    at SendStream.send (/Users/Todd/Documents/molab-rhino-api/interface/node_modules/serve-static/node_modules/send/index.js:564:19)
    at onstat (/Users/Todd/Documents/molab-rhino-api/interface/node_modules/serve-static/node_modules/send/index.js:624:10)
    at FSReqWrap.oncomplete (fs.js:117:15)`

Photos contained within tweets **are immediately** displayed onto the rhino.

**Comment by 05tb** [comment]
Direct photo streaming onto the rhino only worked is specific cases, ignore the above.
Have changed this so that both the video and photo streaming work but only when on the `led-mapping.html` page in the browser. 

The issue is that the code to convert the photo/video into a colour array is in a html page on the front end but this need to be on the server side. 
Ideally a tweet would be received and the colour array would be generated on the server from the video/photo and then pass the colour array directly the python server. 

The code in `led-mapping.js` used to make the colour array needs to be move to the server side.

**Comment by 05tb** [comment]
No longer required in the project
