### ISSUE TITLE
Automatic deployment - not working 

### ISSUE THREAD

**Issue by 05tb** [met-office-lab/molab-rhino-api#45]
The web hook sent from the git repo times out at the npm install step.
I think maybe the npm install takes too long and the serve times out during this step.

**Comment by 05tb** [comment]
```
restarting servers...
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: connection refused: localtunnel.me:35843 (check your firewall settings)
    at Socket.<anonymous> (/home/pi/github/molab-rhino-api/deploy/node_modules/localtunnel/lib/TunnelCluster.js:47:32)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at emitErrorNT (net.js:1269:8)
    at nextTickCallbackWith2Args (node.js:442:9)
    at process._tickCallback (node.js:356:17)
```
