### ISSUE TITLE
Historic tweets causing server crash

### ISSUE THREAD

**Issue by 05tb** [met-office-lab/molab-rhino-api#48]
Function `history` in `app.js` throws an error on line 48. 

I believe this is because it cannot search Twitter for previous tweets due to no internet access.

However when running the code purely on the raspberry pi this error is thrown even when it has access to the Internet.

**Comment by 05tb** [comment]
Was just an internet issues as far as I am aware

**Comment by 05tb** [comment]
```
/home/pi/github/molab-rhino-api/interface/src/app.js:48
        var ordered = tweets.statuses.reverse();
                            ^

TypeError: Cannot read property 'statuses' of undefined
    at /home/pi/github/molab-rhino-api/interface/src/app.js:48:29
    at Request._callback (/home/pi/github/molab-rhino-api/interface/node_modules/twitter/lib/twitter.js:138:14)
    at self.callback (/home/pi/github/molab-rhino-api/interface/node_modules/request/request.js:187:22)
    at emitOne (events.js:77:13)
    at Request.emit (events.js:169:7)
    at Request.onRequestError (/home/pi/github/molab-rhino-api/interface/node_modules/request/request.js:813:8)
    at emitOne (events.js:77:13)
    at ClientRequest.emit (events.js:169:7)
    at TLSSocket.socketErrorListener (_http_client.js:267:9)
    at emitOne (events.js:77:13)
```
